name: Build with pdflatex
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile paper-conference.tex
        uses: dante-ev/latex-action@master
        with:
          working_directory: paper/
          root_file: main.tex
          compiler: pdflatex
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: main.pdf
        if: always()          
